#!/bin/bash
clear
#--------[ DONO @DuckSSH_ofc ]-----------#
source ShellBot.sh
touch lista
[[ -z $1 ]] && {
    clear && echo "INFORME O TOKEN" && return 0
}
# Informações Server 2
ip_server2="SEU-IP-AQUI"
senha_server2="SUA-SENHA-AQUI"
# Informações Server 3
ip_server3="SEU-IP-AQUI"
senha_server3="SUA-SENHA-AQUI"
[[ ! -e RESET ]] && touch RESET
api_bot=$1
ShellBot.init --token "$api_bot" --monitor --flush
ShellBot.username

# - Funcao menu
menu() {
    local msg
        msg+="<b>⚠️ | Estamos em manutenção</b>\n"
msg+="O bot está em modo de manutenção. Provavelmente isso aconteceu porque estamos fazendo melhorias em algum recurso do bot ou no bot em si.\n"
msg+="Volte mais tarde, provavelmente o bot estará ativo novamente até lá :)"
  done
done
